#spring.config.import: optional:secrets.yml

server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookstoregroup174@gmail.com
    password: oytw bgpn nexr cpvc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/jobhunt_db
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/change-log.xml
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: localhost:9200
    redis:
      host: localhost
      port: 6379


logging:
  level:
    org.springframework.mail: DEBUG
    com.edu.hcmute: TRACE
    root: INFO