server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_app?useSSL=false&serverTimezone=UTC
    username: utestudent
    password: utestudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      properties:
        hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
app:
  security:
    cors:
      allowedOrigin: "*"
      allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
      allowedHeaders: "Content-Type, Authorization"
      allowedCredentials: false
      corsConfiguration: "/**"
logging:
  level:
    com.edu.hcmute: TRACE
    root: INFO