spring.config.import: optional:secrets.yml

server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_app
    username: utestudent
    password: utestudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/change-log.xml
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    com.edu.hcmute: TRACE
    root: INFO