spring.config.import: optional:secrets.yml

server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:

  main:
    banner-mode: off
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_app
    username: root
    password: thuthao
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: jobhuntadm@gmail.com
    password: tbco crpw inyc pmku
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/change-log.xml
  data:
#    elasticsearch:
#      cluster-name: docker-cluster
#      cluster-nodes: localhost:9200
    redis:
      host: localhost
      port: 6379


logging:
  level:
    com.edu.hcmute: TRACE
    root: INFO