spring.config.import: optional:secrets.yml

server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/recruitment_app
    username: utestudent
    password: utestudent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379

app:
  security:
    cors:
      allowedOrigin: "*"
      allowedMethods: "GET, POST, PUT, DELETE, OPTIONS"
      allowedHeaders: "Content-Type, Authorization"
      allowedCredentials: false
      corsConfiguration: "/**"
logging:
  level:
    com.edu.hcmute: TRACE
    root: INFO